### ISSUE TITLE
Hint: using travis with contao 4.5+

### ISSUE THREAD

**Issue by fatcrobat** [terminal42/header-replay-bundle#10]
This is not an issue, but should be maybe added as a knowledge note.

When using your custom bundle with continious integration platforms like travis ci the following build error will appear:

> Problem 1
    - contao/core-bundle 4.5.0 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.1 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.2 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - contao/core-bundle 4.5.3 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - terminal42/header-replay-bundle 1.3.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - terminal42/header-replay-bundle 1.4.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - terminal42/header-replay-bundle 1.4.1 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - friendsofsymfony/http-cache 2.1.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.1.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.2 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - Installation request for contao/core-bundle 4.5.* -> satisfiable by contao/core-bundle[4.5.0, 4.5.1, 4.5.2, 4.5.3].Problem 1
    - contao/core-bundle 4.5.0 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.1 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.2 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - contao/core-bundle 4.5.3 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - terminal42/header-replay-bundle 1.3.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - terminal42/header-replay-bundle 1.4.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - terminal42/header-replay-bundle 1.4.1 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1].
    - friendsofsymfony/http-cache 2.1.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.1.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.2 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - Installation request for contao/core-bundle 4.5.* -> satisfiable by contao/core-bundle[4.5.0, 4.5.1, 4.5.2, 4.5.3].

To fix this, all bundles that support contao 4.5 and should be tested with travis for example, must have the composer dev requirement for the **`php-http/guzzle6-adapter`**. Here an working example from our utils-bundle

```
{
  "name": "heimrichhannot/contao-utils-bundle",
  "type": "contao-bundle",
  "description": "This bundle offers various utility functionality for the Contao CMS.",
  "license": "LGPL-3.0-or-later",
  "require": {
    "php": ">=7.1.0",
    "contao/core-bundle": "^4.4",
    "heimrichhannot/contao-request": "^1.2"
  },
  "require-dev": {
    "contao/manager-plugin": "^2.0",
    "friendsofphp/php-cs-fixer": "^2.2",
    "phpunit/phpunit": "^6.0",
    "satooshi/php-coveralls": "^1.0",
    "contao/test-case": "^1.1",
    "php-http/guzzle6-adapter": "^1.1"
  }
}
```

Composer inside travis is looking for a virtual adapter named `php-http/client-implementation`. As your package is tested stand-alone, the you must pick any of the clients or adapters provided by PHP-HTTP. 
This bundle uses `php-http/guzzle6-adapter`, other popular choices are `php-http/curl-client`. 

Maybe this hint should be added to the README.md or/and Contao 4.5+ README.md as well?

**Comment by Toflar** [comment]
The header-replay-bundle is a bundle that depends on the `friendsofsymfony/http-cache-bundle` which itself requires any `php-http/client-implemenation`. It's not a requirement of this bundle, it's a requirement of the FOS bundle/library.

**Comment by fatcrobat** [comment]
Found this issue at https://github.com/FriendsOfSymfony/FOSHttpCache/issues/374:

> php-http/client-implementation is a virtual package. see http://docs.php-http.org/en/latest/httplug/users.html - you need to install one of the adapters.

In `friendsofsymfony/http-cache` composer.json the dev requirement for  `"php-http/guzzle6-adapter": "^1.0.0"` is provided. But as we test our bundle in a nutshell, the virtual adapter is not loaded yet, but already required.

**Comment by Toflar** [comment]
Yeah, it's the same here. I also use guzzle in my dev-requirements to test the bundle. You need to require one yourself. I don't see the issue here?

**Comment by fatcrobat** [comment]
@Toflar See the title, it is not an issue, just an hint for other developers who try to test their bundle standalone and maybe this hint makes them happier using contao and not seek themself? :)

**Comment by Toflar** [comment]
Ah, I see. Yeah sure, we can add a hint in the README 😄

**Comment by Toflar** [comment]
Added in https://github.com/terminal42/header-replay-bundle/commit/2f3a3a367a03b56d6c5ec29eb9ec2e520a37048b.
