### ISSUE TITLE
RedirectResponseExceptions are ignored since 1.4.0

### ISSUE THREAD

**Issue by fritzmg** [terminal42/header-replay-bundle#13]
See problem description in https://github.com/contao/core-bundle/issues/1373

Not sure what the problem within the header-replay-bundle would be though ;)

**Comment by fritzmg** [comment]
`composer.json` and `composer.lock` of an example project: [project.zip](https://github.com/terminal42/header-replay-bundle/files/1728475/project.zip)

**Comment by Toflar** [comment]
Yes, this was changed here: https://github.com/terminal42/header-replay-bundle/pull/7 and is correct in that case for other reasons, also see https://github.com/contao/core-bundle/issues/1307.

**Comment by fritzmg** [comment]
Hm yeah, I cannot contribute anything to that, since I don't understand what the replay-header-bundle actually does 😬.

What I also don't understand is: even though `initializeFramework` throws a `RedirectResponseException` (through my hook in this case), `FrontendIndex::run` is still executed which throws the `PageNotFoundException`.

**Comment by Toflar** [comment]
Yeah, your hook is triggered during the preflight response process and then the real request is processed which doesn't know anything anymore about your redirect.
@aschempp maybe I should still set the response on the event in case the preflight request response is of `3xx` status code? Would make sense to me, wdyt?

**Comment by Toflar** [comment]
Does https://github.com/terminal42/header-replay-bundle/commit/5401285863e861a2f191bae79c7231c7d9e1ac45 fix your problem?

**Comment by fritzmg** [comment]
Yep 👍  :)
