### ISSUE TITLE
1.2.0 verursacht bei Verwendung der Dev-Umgebung ein Problem mit der Symfony-Debugbar

### ISSUE THREAD

**Issue by OMOSde** [terminal42/header-replay-bundle#3]
Contao 4.4.2 (standard-edition)
Update durch Composer von header-replay-bundle 1.1.1 auf 1.2.0

vorerst gelöst durch einen Conflict-Eintrag in der composer.json des Projektes

![peetz ai-designer net-app_dev php-contao-login](https://user-images.githubusercontent.com/2035628/29073504-266594a6-7c4c-11e7-8c68-d5439d1b2072.png)

**Comment by Toflar** [comment]
Fixed in 30c295c6ea2b0bfd3053ab2e9b2b29b49952fbaf.
