### ISSUE TITLE
Version 1.4 not backwards compatible

### ISSUE THREAD

**Issue by leofeyer** [terminal42/header-replay-bundle#8]
Using Contao 4.4 with version 1.4 of the header-replay-bundle breaks Contao's autologin functionality, therefore I assume that version 1.4 is not backwards compatible?

**Comment by Toflar** [comment]
Imho it's fully BC, please provide more info.

**Comment by leofeyer** [comment]
* Install Contao 4.4 with version 1.3 of the header replay bundle.
* Log in in the front end and create an autologin cookie.
* Update to version 1.4 of the header replay bundle.
* Make sure the PHP session cookie is gone (e.g. log out of the back end).
* Open the front end.

Expected: I am logged in automatically.
Actual: I am not logged in automatically.

**Comment by leofeyer** [comment]
In case it helps: if I reload the page twice (meaning upon the third request), I am actually logged in automatically with version 1.4. With version 1.3 I am logged in automatically upon the first request.

**Comment by aschempp** [comment]
Most likely because the user is authenticated but the authentication cookie is lost in the preflight request :-(

**Comment by Toflar** [comment]
The cookie is not lost, it's replayed onto the second request.

**Comment by aschempp** [comment]
Is it? If the initial request was not successful?

**Comment by Toflar** [comment]
Of course not, then it's just passed on to the application, not a problem of the bundle anymore.

**Comment by Toflar** [comment]
I don't think there's ever been a BC break here but I've adjusted the way cookies are replayed in https://github.com/terminal42/header-replay-bundle/commit/1f1f504965873420ef50161980b519ecafebc8a8 so the upcoming 1.4.2 might fix your issue.

**Comment by Toflar** [comment]
I tried to reproduce, works perfectly fine in both versions, 1.4.1 as well as the current 1.4.2 hotfix.

**Comment by Toflar** [comment]
Even 1.4.0 works.

**Comment by joeherold** [comment]
@Toflar works, no problem so far with Contao 4.4.13 and `"terminal42/header-replay-bundle": "dev-hotfix/1.4.2 as 1.3.2"`

**Comment by joeherold** [comment]
ups, my auto login page runs on a different subdomain. so this will not reproduce the issue described by @leofeyer

**Comment by leofeyer** [comment]
Now it works with version 1.4.1 on my system, too. WTF?

**Comment by Toflar** [comment]
Ok, releasing then :-)
